config-version: 0.025 # do not change

# --- CLAIMING ---
claim-world: 'world' # REQUIRES RESTART: the world in which claims can be made

# --- MAP PLUGINS ---
enable-Pl3xMap: true # REQUIRES RESTART: enables the plugin to connect to the Pl3xMap plugin (if you have it installed)

# --- COMMANDS ---
enable-gc-confirm: true # sometimes require a command to be confirmed via /gc confirm

# --- CHAT ---
country-prefix-enabled: true # whether to display a country's chosen prefix before its citizens' messages
chat-prefix: '§8[GeoCountries] ' # text before every plugin chat and console message
country-prefix-format: "%s[%s]" # format of country prefix in chat before usernames, first %s = colour, second %s = country prefix

# --- SOUND ---
sound-effects: true # play notification sound effects (on war declared, chat notif, etc)

# --- INVITES ---
max-citizenship-applications: 10 # max number of sent citizenship applications allowed per player, -1=infinite
max-faction-invites: 10 # max number of sent pending faction invites allowed per faction, -1=infinite

# --- STRING LENGTHS ---
chat-response-min: 1 # min allowed length of chat message when player asked to type in chat
chat-response-max: 150  # max allowed length of chat message when player asked to type in chat
country-name-min: 2 # min allowed length of new country names
country-name-max: 40 # max allowed length of new country names
country-motto-min: 1 # min allowed length of country mottos
country-motto-max: 50 # max allowed length of country mottos
country-prefix-min: 1 # min allowed length of new country prefixes
country-prefix-max: 10 # max allowed length of new country prefixes
faction-name-min: 2 # min allowed length of new faction names
faction-name-max: 40 # max allowed length of new faction names

# --- DEBUG ---
debug-logging: false # more logging in server console for debugging
debug-mode: false # disables several checks and features for easier plugin development
