config-version: 0.021 # do not change

enable-Pl3xMap: true # enables the plugin to connect to the Pl3xMap plugin (if you have it installed)

debug-logging: false # more logging in server console for debugging
debug-mode: false # disables several checks and features for easier plugin development

enable-gc-confirm: true # sometimes require a command to be confirmed via /gc confirm

chat-prefix: '§8[GeoCountries] ' # text before every plugin chat and console message

country-prefix-enabled: true # whether to display a country's chosen prefix before its citizens' messages
country-prefix-format: "%s[%s]" # format of country prefix in chat before usernames, first %s = colour, second %s = country prefix
country-prefix-min: 1 # min allowed length of a country's chosen prefix
country-prefix-max: 10 # max allowed length of a country's prefix

sound-effects: true # play notification sound effects (on war declared, chat notif, etc)

max-citizenship-applications: 10 # max number of sent citizenship applications allowed per person, -1=infinite

chat-response-min: 1 # min allowed length of chat message when player asked to type in chat
chat-response-max: 150  # max allowed length of chat message when player asked to type in chat
country-name-min: 2 # min allowed length of new country names
country-name-max: 35 # max allowed length of new country names
country-motto-min: 1 # min allowed length of country mottos
country-motto-max: 50 # max allowed length of country mottos