config-version: 0.0204 # do not change

debug-logging: false # more logging in server console for debugging
debug-mode: false # disables several checks and features for easier plugin development

chat-prefix: '§8[GeoCountries] ' # text before every plugin chat and console message

sound-effects: true # play notification sound effects (on war declared, chat notif, etc)

chat-response-min: 1 # min allowed length of chat message when player asked to type in chat
chat-response-max: 150  # max allowed length of chat message when player asked to type in chat
country-name-min: 2 # min allowed length of new country names
country-name-max: 35 # max allowed length of new country names
